# Generated by Django 5.2.4 on 2025-08-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_specialrequest_submitted_at_alter_schedule_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='ward',
            field=models.IntegerField(),
        ),
    ]
