# Generated by Django 5.2.4 on 2025-08-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0003_alter_schedule_ward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compostrequest',
            old_name='address',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='compostrequest',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='compostrequest',
            name='date',
        ),
        migrations.RemoveField(
            model_name='compostrequest',
            name='is_collected',
        ),
        migrations.RemoveField(
            model_name='compostrequest',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='compostrequest',
            name='time',
        ),
        migrations.RemoveField(
            model_name='compostrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='compostrequest',
            name='contact',
            field=models.CharField(default='N/A', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compostrequest',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='compostrequest',
            name='name',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compostrequest',
            name='quantity',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compostrequest',
            name='waste_type',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
    ]
